services:
  go:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - social-db:/app/internal/database
    restart: unless-stopped

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - go
    restart: unless-stopped
volumes:
  social-db:
